server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${database}?serverTimezone=Asia/Seoul
    username: ${name}
    password: ${pw}

#  mvc: #뷰리졸버 설정 이거는 mustach라이브러리가 알아서 설정해줌
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl






  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${googleId}
            client-secret: ${googlePw}
            scope:
              - email
              - profile


          # 네이버는 OAuth2.0 공식 지원대상이 아니라서 provider 설정이 필요하다.
          # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.
          naver:
            client-id: ${naverId}
            client-secret: ${naverPw}
            scope:
              - name
              - email
              - profile_image
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #http://localhost:8080/login/oauth2/code 여기까지는 고정이다 그이후에는 맞느걸 써주면 된다

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인창으로 이동
            token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받을려면 이주소를 사용
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 정보를 받을려고 사용
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
            #response={id=Dvs8taWRay7edNd4KCEwkoYNq-nWN4kGnh5ybIL0XbA, email=codo7717@naver.com, name=최치언}
